### ISSUE TITLE
Pickle File of E-Z Reader Model

### ISSUE THREAD

**Issue by kishanmaharaj** [oeberle/task_gaze_transformers#1]
Can you please provide the "kneser_ney_eval_from_trace.pkl" file?

**Comment by oeberle** [comment]
You should be able to access our pickle files using  `main/get_osf_data.sh`. 

Alternatively, you can directly access the files on osf by downloading ` dfs_others_{sst/wiki}.zip `, e.g. https://osf.io/b627h (for SST).
